### PR TITLE
Correct links in document, prepare code for a new structure of the card.js's iframe

### PR DESCRIPTION
**Pull request by guzzilar**
PR Purpose
=========
- Correct links in the README.md file.
- Enhance the code, prepare it for a new structure of the card.js's iframe

#### The effect after you merge this PR.
It will be possible to move all of card.js files inside `card.omise.co` to `cdn.omise.co/...`  

#### The deployment instruction
The steps to deploy are as follows:
- Deploy `/build/javascripts/card.js` to `https://cdn.omise.co/`
- Deploy everything inside `/build` folder to `https://cdn.omise.co/card-2.0`  
  (you could remove `https://cdn.omise.co/card-2.0/javascripts/card.js` because we will keep it outside of this folder (see above)).

Noted:
- if you want to change the name of the iframe's folder (`https://cdn.omise.co/card-2.0`) you could change it in `source/javascripts/card-2.0.0.js.coffee`  
  Line 10: `@directory    = "/card-2.0"`
- You have to re-build again after merge this PR.

### CODE REVIEW

**Comment by guzzilar** [comment]
Oops, wait it failed in CircleCI

**Comment by guzzilar** [comment]
Ok, fine. let's continue review :smile:

**Comment by fred** [comment]
Great!

**Comment by guzzilar** [comment]
FYI: for the committed `0372d27`
At the begin, I created a new file `source/javascripts/card-2.0.0.js.coffee` for dev card.js version 2 and leave the old one in `source/javascripts/card.js.erb`.

So, when the committed `0372d27` comes, I decided to remove `source/javascripts/card-2.0.0.js.coffee` and moved code into `source/javascripts/card.js.erb`. Also, changed the file extension from `card.js.erb` to `card.js.coffee`.  

So, when you look in the Git file changed. It will show as
- renamed `source/javascripts/card-2.0.0.js.coffee` to `source/javascripts/card.js.coffee`
- removed `source/javascripts/card.js.erb`

**Pull request merged**
